// Positive words commonly found in workplace feedback (scored 1-3)
export const POSITIVE_WORDS: Record<string, number> = {
    // Strong positive (3)
    'excelente': 3,
    'perfeito': 3,
    'maravilhoso': 3,
    'incrivel': 3,
    'incrível': 3,
    'fantastico': 3,
    'fantástico': 3,
    'extraordinario': 3,
    'extraordinário': 3,
    'excepcional': 3,
    'sensacional': 3,
    'espetacular': 3,
    'amo': 3,
    'adoro': 3,
    'adorei': 3,
    'amei': 3,
    'apaixonado': 3,

    // Moderate positive (2)
    'otimo': 2,
    'ótimo': 2,
    'muito bom': 2,
    'satisfeito': 2,
    'feliz': 2,
    'contente': 2,
    'motivado': 2,
    'engajado': 2,
    'comprometido': 2,
    'realizado': 2,
    'orgulhoso': 2,
    'empolgado': 2,
    'entusiasmado': 2,
    'inspirado': 2,
    'apoiado': 2,
    'valorizado': 2,
    'reconhecido': 2,
    'respeitado': 2,
    'confiante': 2,
    'seguro': 2,
    'tranquilo': 2,
    'confortavel': 2,
    'confortável': 2,
    'agradecido': 2,
    'grato': 2,
    'impressionado': 2,
    'admirado': 2,
    'encantado': 2,

    // Mild positive (1)
    'bom': 1,
    'boa': 1,
    'bem': 1,
    'legal': 1,
    'bacana': 1,
    'interessante': 1,
    'positivo': 1,
    'adequado': 1,
    'razoavel': 1,
    'razoável': 1,
    'satisfatorio': 1,
    'satisfatório': 1,
    'agradavel': 1,
    'agradável': 1,
    'util': 1,
    'útil': 1,
    'produtivo': 1,
    'eficiente': 1,
    'eficaz': 1,
    'competente': 1,
    'profissional': 1,
    'colaborativo': 1,
    'cooperativo': 1,
    'disponivel': 1,
    'disponível': 1,
    'acessivel': 1,
    'acessível': 1,
    'atencioso': 1,
    'cordial': 1,
    'educado': 1,
    'prestativo': 1,
    'dedicado': 1,
    'esforçado': 1,
    'capaz': 1,
    'crescimento': 1,
    'desenvolvimento': 1,
    'aprendizado': 1,
    'oportunidade': 1,
    'oportunidades': 1,
    'progresso': 1,
    'melhoria': 1,
    'melhorar': 1,
    'evoluir': 1,
    'evolucao': 1,
    'evolução': 1,
    'sucesso': 1,
    'conquista': 1,
    'realizacao': 1,
    'realização': 1,
    'claro': 1,
    'clara': 1,
    'transparente': 1,
    'objetivo': 1,
    'justo': 1,
    'justa': 1,
    'equilibrado': 1,
    'flexivel': 1,
    'flexível': 1,
    'autonomia': 1,
    'liberdade': 1,
    'confianca': 1,
    'confiança': 1,
    'apoio': 1,
    'suporte': 1,
    'ajuda': 1,
    'parceria': 1,
    'trabalho em equipe': 1,
    'equipe': 1,
    'time': 1,
    'unido': 1,
    'harmonia': 1,
    'ambiente': 1,
    'cultura': 1,
    'valores': 1,
    'proposito': 1,
    'propósito': 1,
    'significativo': 1,
    'recomendo': 1,
    'recomendaria': 1,
    'gosto': 1,
    'gostei': 1,
    'prazer': 1,
    'orgulho': 1,
};

// Negative words commonly found in workplace feedback (scored -1 to -3)
export const NEGATIVE_WORDS: Record<string, number> = {
    // Strong negative (-3)
    'pessimo': -3,
    'péssimo': -3,
    'horrivel': -3,
    'horrível': -3,
    'terrivel': -3,
    'terrível': -3,
    'insuportavel': -3,
    'insuportável': -3,
    'odio': -3,
    'ódio': -3,
    'odeio': -3,
    'detesto': -3,
    'desprezo': -3,
    'tóxico': -3,
    'toxico': -3,
    'abusivo': -3,
    'assedio': -3,
    'assédio': -3,
    'humilhacao': -3,
    'humilhação': -3,
    'humilhante': -3,
    'discriminacao': -3,
    'discriminação': -3,
    'injustica': -3,
    'injustiça': -3,
    'desumano': -3,
    'exploração': -3,
    'exploracao': -3,

    // Moderate negative (-2)
    'ruim': -2,
    'mal': -2,
    'mau': -2,
    'insatisfeito': -2,
    'frustrado': -2,
    'frustração': -2,
    'frustracao': -2,
    'decepcionado': -2,
    'decepcao': -2,
    'decepção': -2,
    'desanimado': -2,
    'desmotivado': -2,
    'desengajado': -2,
    'estressado': -2,
    'estresse': -2,
    'ansioso': -2,
    'ansiedade': -2,
    'preocupado': -2,
    'preocupacao': -2,
    'preocupação': -2,
    'infeliz': -2,
    'triste': -2,
    'deprimido': -2,
    'esgotado': -2,
    'burnout': -2,
    'exausto': -2,
    'cansado': -2,
    'sobrecarregado': -2,
    'sobrecarga': -2,
    'desvalorizado': -2,
    'ignorado': -2,
    'excluido': -2,
    'excluído': -2,
    'isolado': -2,
    'desrespeitado': -2,
    'desrespeito': -2,
    'negligenciado': -2,
    'abandonado': -2,
    'inseguro': -2,
    'insegurança': -2,
    'inseguranca': -2,
    'instavel': -2,
    'instável': -2,
    'instabilidade': -2,
    'incerto': -2,
    'incerteza': -2,
    'confuso': -2,
    'confusão': -2,
    'confusao': -2,
    'perdido': -2,
    'desorientado': -2,
    'incompetente': -2,
    'incompetencia': -2,
    'incompetência': -2,
    'despreparo': -2,
    'despreparado': -2,
    'ineficiente': -2,
    'improdutivo': -2,
    'caos': -2,
    'caotico': -2,
    'caótico': -2,
    'desorganizado': -2,
    'desorganizacao': -2,
    'desorganização': -2,
    'bagunca': -2,
    'bagunça': -2,

    // Mild negative (-1)
    'problema': -1,
    'problemas': -1,
    'dificuldade': -1,
    'dificuldades': -1,
    'dificil': -1,
    'difícil': -1,
    'complicado': -1,
    'complexo': -1,
    'desafio': -1,
    'desafiador': -1,
    'fraco': -1,
    'fraca': -1,
    'lento': -1,
    'lenta': -1,
    'atrasado': -1,
    'atraso': -1,
    'falta': -1,
    'falha': -1,
    'falhas': -1,
    'erro': -1,
    'erros': -1,
    'deficiente': -1,
    'limitado': -1,
    'limitacao': -1,
    'limitação': -1,
    'restricao': -1,
    'restrição': -1,
    'burocracia': -1,
    'burocratico': -1,
    'burocrático': -1,
    'moroso': -1,
    'demora': -1,
    'demorado': -1,
    'devagar': -1,
    'pouco': -1,
    'poucos': -1,
    'escasso': -1,
    'escassa': -1,
    'ausente': -1,
    'ausencia': -1,
    'ausência': -1,
    'nenhum': -1,
    'nenhuma': -1,
    'inexistente': -1,
    'precario': -1,
    'precário': -1,
    'insuficiente': -1,
    'inadequado': -1,
    'antiquado': -1,
    'ultrapassado': -1,
    'obsoleto': -1,
    'chato': -1,
    'tedioso': -1,
    'monotono': -1,
    'monótono': -1,
    'repetitivo': -1,
    'cansativo': -1,
    'entediado': -1,
    'regular': -1,
    'mediano': -1,
    'mediocre': -1,
    'medíocre': -1,
    'mais ou menos': -1,
    'nem bom nem ruim': -1,
    'poderia melhorar': -1,
    'precisa melhorar': -1,
    'a desejar': -1,
    'deixa a desejar': -1,
    'melhorar': -1,
    'reclamacao': -1,
    'reclamação': -1,
    'reclamar': -1,
    'critica': -1,
    'crítica': -1,
    'criticar': -1,
    'queixa': -1,
    'queixar': -1,
    'pressao': -1,
    'pressão': -1,
    'cobranca': -1,
    'cobrança': -1,
    'rigido': -1,
    'rígido': -1,
    'inflexivel': -1,
    'inflexível': -1,
    'controlador': -1,
    'microgerenciamento': -1,
    'fofoca': -1,
    'politicagem': -1,
    'favoritismo': -1,
    'panelinha': -1,
};

// Negation words that invert sentiment
export const NEGATION_WORDS: string[] = [
    'nao', 'não', 'nem', 'nunca', 'jamais', 'tampouco',
    'nenhum', 'nenhuma', 'nada', 'sem', 'contra',
];

// Intensifiers that amplify sentiment (multipliers)
export const INTENSIFIERS: Record<string, number> = {
    'muito': 1.5,
    'demais': 1.5,
    'bastante': 1.3,
    'extremamente': 2.0,
    'super': 1.8,
    'hiper': 2.0,
    'mega': 1.8,
    'ultra': 2.0,
    'totalmente': 1.5,
    'completamente': 1.5,
    'absolutamente': 1.5,
    'realmente': 1.3,
    'verdadeiramente': 1.3,
    'incrivelmente': 1.8,
    'absurdamente': 2.0,
    'especialmente': 1.3,
    'particularmente': 1.3,
    'cada vez mais': 1.3,
    'mais': 1.2,
    'tao': 1.3,
    'tão': 1.3,
    'bem': 1.2,
    'sempre': 1.3,
    'constantemente': 1.3,
};

// Diminishers that reduce sentiment (multipliers)
export const DIMINISHERS: Record<string, number> = {
    'pouco': 0.5,
    'um pouco': 0.5,
    'quase': 0.7,
    'ligeiramente': 0.5,
    'levemente': 0.5,
    'razoavelmente': 0.7,
    'moderadamente': 0.7,
    'relativamente': 0.8,
    'parcialmente': 0.6,
    'meio': 0.5,
    'mais ou menos': 0.5,
    'as vezes': 0.6,
    'às vezes': 0.6,
    'ocasionalmente': 0.6,
    'raramente': 0.4,
    'dificilmente': 0.4,
    'apenas': 0.7,
    'somente': 0.7,
    'so': 0.7,
    'só': 0.7,
};

// Portuguese stop words for preprocessing
export const STOP_WORDS: string[] = [
    'a', 'o', 'e', 'de', 'da', 'do', 'em', 'um', 'uma', 'para', 'com', 'por',
    'que', 'se', 'na', 'no', 'os', 'as', 'dos', 'das', 'ao', 'aos', 'pela',
    'pelo', 'pelas', 'pelos', 'sua', 'seu', 'suas', 'seus', 'ela', 'ele',
    'elas', 'eles', 'nos', 'nas', 'este', 'esta', 'estes', 'estas', 'esse',
    'essa', 'esses', 'essas', 'aquele', 'aquela', 'aqueles', 'aquelas',
    'isto', 'isso', 'aquilo', 'qual', 'quais', 'quanto', 'quanta', 'quantos',
    'quantas', 'onde', 'quando', 'como', 'porque', 'pois', 'entao', 'então',
    'ja', 'já', 'ainda', 'mesmo', 'depois', 'antes', 'agora', 'hoje', 'ontem',
    'amanha', 'amanhã', 'tambem', 'também', 'so', 'só', 'entre', 'sobre',
    'ate', 'até', 'desde', 'durante', 'etc', 'ser', 'ter', 'estar', 'ir',
    'foi', 'era', 'seria', 'fui', 'sao', 'são', 'tem', 'tinha', 'teria',
    'esta', 'estava', 'estaria', 'vai', 'ia', 'iria', 'pode', 'podia',
    'poderia', 'deve', 'devia', 'deveria', 'quer', 'queria', 'quereria',
    'sabe', 'sabia', 'saberia', 'faz', 'fazia', 'faria', 'diz', 'dizia',
    'diria', 'vem', 'vinha', 'viria', 'acho', 'achei', 'achava', 'penso',
    'pensei', 'pensava', 'sinto', 'senti', 'sentia', 'vejo', 'vi', 'via',
    'me', 'te', 'lhe', 'se', 'mim', 'ti', 'si', 'meu', 'teu', 'dele', 'dela',
    'nosso', 'vosso', 'minha', 'tua', 'nossa', 'vossa', 'minhas', 'tuas',
    'nossas', 'vossas', 'meus', 'teus', 'nossos', 'vossos', 'mais', 'menos',
    'outro', 'outra', 'outros', 'outras', 'cada', 'todo', 'toda', 'todos',
    'todas', 'algum', 'alguma', 'alguns', 'algumas', 'qualquer', 'quaisquer',
];

// Comment field mapping for the survey
export const COMMENT_FIELDS = [
    { key: 'comentariosInteresse', label: 'Interesse no Cargo', relatedScore: 'interesseNoCargo' },
    { key: 'comentariosContribuicao', label: 'Contribuição', relatedScore: 'contribuicao' },
    { key: 'comentariosAprendizado', label: 'Aprendizado e Desenvolvimento', relatedScore: 'aprendizado' },
    { key: 'comentariosFeedback', label: 'Feedback', relatedScore: 'feedback' },
    { key: 'comentariosInteracao', label: 'Interação com Gestor', relatedScore: 'interacaoGestor' },
    { key: 'comentariosClareza', label: 'Clareza sobre Carreira', relatedScore: 'clarezaCarreira' },
    { key: 'comentariosExpectativa', label: 'Expectativa de Permanência', relatedScore: 'expectativaPermanencia' },
    { key: 'enpsComentario', label: 'eNPS', relatedScore: 'enps' },
];
